using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hotel.org.HotelSeedData
{
    public class HotelData : IEntityTypeConfiguration<Hotel.org.Models.Hotels>
    {
        public void Configure(EntityTypeBuilder<Hotel.org.Models.Hotels> builder)
        {
            builder.HasData(
                new Hotel.org.Models.Hotels
                {
                    Id = 1,
                    Name = "The Ritz-Carlton, Tokyo",
                    Address = "Tokyo Midtown 9-7-1 Akasaka Minato-ku",
                    City = "Tokyo",
                    PostalCode = "107-6245",
                    Country = "Japan",
                    ContactEmail = "info@ritzcarlton-tokyo.com",
                    ContactPhone = "+81334231811",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 245,
                    RoomTypes = "Deluxe, Executive, Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/luxury_resort.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 600,
                    Rating = 4,
                    Description = "Luxurious accommodations with breathtaking views of Tokyo.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 35.6655,
                    longitute = 139.7297
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 2,
                    Name = "Hotel de Paris Monte-Carlo",
                    Address = "Place du Casino",
                    City = "Monte Carlo",
                    PostalCode = "98000",
                    Country = "Monaco",
                    ContactEmail = "info@montecarlosbm.com",
                    ContactPhone = "+37798062121",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 182,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/mountain_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 750,
                    Rating = 3,
                    Description = "Experience the grandeur and elegance in the heart of Monaco.",
                    lat = 43.7384,
                    longitute = 7.4256
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 3,
                    Name = "The Plaza Hotel",
                    Address = "768 5th Ave",
                    City = "New York",
                    PostalCode = "10019",
                    Country = "USA",
                    ContactEmail = "info@theplazany.com",
                    ContactPhone = "+12127594600",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = false,
                    NumberOfRooms = 282,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/city_center_hotel.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 900,
                    Rating = 5,
                    Description = "An iconic luxury hotel in the heart of New York City.",
                    lat = 40.7645,
                    longitute = -73.9742
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 4,
                    Name = "Burj Al Arab",
                    Address = "Jumeirah St, Umm Suqeim 3",
                    City = "Dubai",
                    PostalCode = "",
                    Country = "United Arab Emirates",
                    ContactEmail = "info@burjalarab.com",
                    ContactPhone = "+97143017777",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 202,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/coastal_retreat.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 1200,
                    Rating = 2,
                    Description = "The epitome of Arabian luxury in Dubai.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 25.1412,
                    longitute = 55.1853
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 5,
                    Name = "The Savoy Hotel",
                    Address = "Strand",
                    City = "London",
                    PostalCode = "WC2R 0EZ",
                    Country = "United Kingdom",
                    ContactEmail = "info@savoylondon.com",
                    ContactPhone = "+442074836000",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 267,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/rural_farmstay.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 800,
                    Rating = 2,
                    Description = "Historic luxury hotel in the heart of London.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 51.5100,
                    longitute = -0.1200
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 6,
                    Name = "Raffles Hotel",
                    Address = "1 Beach Road",
                    City = "Singapore",
                    PostalCode = "189673",
                    Country = "Singapore",
                    ContactEmail = "info@raffles.com",
                    ContactPhone = "+6563371886",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 115,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/urban_boutique_hotel.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 700,
                    Rating = 3,
                    Description = "A historic hotel that epitomizes the romance of the Far East.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 1.2945,
                    longitute = 103.8545
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 7,
                    Name = "Four Seasons Hotel George V",
                    Address = "31 Avenue George V",
                    City = "Paris",
                    PostalCode = "75008",
                    Country = "France",
                    ContactEmail = "info@fourseasons.com",
                    ContactPhone = "+33149527000",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 244,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/historic_inn.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 950,
                    Rating = 4,
                    Description = "Luxury accommodations with an Art Deco flair in Paris.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 48.8686,
                    longitute = 2.3005
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 8,
                    Name = "The Oberoi Amarvilas",
                    Address = "Taj East Gate Road, Paktola, Tajganj",
                    City = "Agra",
                    PostalCode = "282001",
                    Country = "India",
                    ContactEmail = "info@oberoihotels.com",
                    ContactPhone = "+915622231515",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 102,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/ski_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 550,
                    Rating = 5,
                    Description = "Luxury hotel with views of the Taj Mahal.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 27.1739,
                    longitute = 78.0421
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 9,
                    Name = "Mandarin Oriental, Bangkok",
                    Address = "48 Oriental Avenue",
                    City = "Bangkok",
                    PostalCode = "10500",
                    Country = "Thailand",
                    ContactEmail = "info@mandarinoriental.com",
                    ContactPhone = "+6626599000",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 331,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/desert_oasis.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 700,
                    Rating = 3,
                    Description = "Historic luxury hotel on the banks of the Chao Phraya River.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 13.7204,
                    longitute = 100.5148
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 10,
                    Name = "Marina Bay Sands",
                    Address = "10 Bayfront Ave",
                    City = "Singapore",
                    PostalCode = "018956",
                    Country = "Singapore",
                    ContactEmail = "info@marinabaysands.com",
                    ContactPhone = "+6566888888",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 2561,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/lakefront_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 450,
                    Rating = 1,
                    Description = "Futuristic hotel with an iconic infinity pool.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                    lat = 1.2834,
                    longitute = 103.8607
                }
            );
        }
    }
}
