using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Hotel.org.HotelSeedData
{
    public class HotelData : IEntityTypeConfiguration<Hotel.org.Models.Hotels>
    {
        public void Configure(EntityTypeBuilder<Hotel.org.Models.Hotels> builder)
        {
            builder.HasData(
                new Hotel.org.Models.Hotels
                {
                    Id = 1,
                    Name = "Luxury Resort",
                    Address = "123 Beachfront Road",
                    City = "Paradise City",
                    PostalCode = "54321",
                    Country = "Tropical Island",
                    ContactEmail = "info@luxuryresort.com",
                    ContactPhone = "+1234567890",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = true,
                    NumberOfRooms = 100,
                    RoomTypes = "Standard, Deluxe, Suite",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/luxury_resort.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 300,
                    Rating = 5,
                    Description = "Experience ultimate luxury and relaxation at our beachfront resort.",
                    NumberOfAdults = Models.Hotels.NumberOfAdultsEnum.Two,
                    NumberOfChildren = Models.Hotels.NumberOfChildrenEnum.Three,
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 2,
                    Name = "Mountain Lodge",
                    Address = "456 Alpine Drive",
                    City = "Mountain Village",
                    PostalCode = "98765",
                    Country = "Alpine Wonderland",
                    ContactEmail = "info@mountainlodge.com",
                    ContactPhone = "+9876543210",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = false,
                    NumberOfRooms = 50,
                    RoomTypes = "Standard, Chalet, Cabin",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/mountain_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 200,
                    Rating = 5,
                    Description = "Escape to the mountains and enjoy cozy accommodations and breathtaking views."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 3,
                    Name = "City Center Hotel",
                    Address = "789 Downtown Avenue",
                    City = "Paradise City",
                    PostalCode = "12345",
                    Country = "Urbania",
                    ContactEmail = "info@citycenterhotel.com",
                    ContactPhone = "+5432109876",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = false,
                    NumberOfRooms = 80,
                    RoomTypes = "Standard, Executive, Suite",
                    CheckInTime = TimeSpan.FromHours(12),
                    RoomImage = "/Images/city_center_hotel.jpg",
                    CheckOutTime = TimeSpan.FromHours(10),
                    AveragePricePerNight = 250,
                    Rating = 2,
                    Description = "Stay in the heart of the city and explore all that Metropolis has to offer."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 4,
                    Name = "Coastal Retreat",
                    Address = "101 Seaside Boulevard",
                    City = "Oceanfront Town",
                    PostalCode = "13579",
                    Country = "Seaside Haven",
                    ContactEmail = "info@coastalretreat.com",
                    ContactPhone = "+9876123450",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = true,
                    NumberOfRooms = 120,
                    RoomTypes = "Standard, Ocean View, Beachfront Villa",
                    CheckInTime = TimeSpan.FromHours(13),
                    RoomImage = "/Images/coastal_retreat.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 280,
                    Rating = 4,
                    Description = "Relax by the sea and enjoy stunning views at our coastal retreat."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 5,
                    Name = "Rural Farmstay",
                    Address = "789 Countryside Lane",
                    City = "Ruralville",
                    PostalCode = "24680",
                    Country = "Countryland",
                    ContactEmail = "info@ruralfarmstay.com",
                    ContactPhone = "+1357924680",
                    Wifi = false,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = false,
                    NumberOfRooms = 20,
                    RoomTypes = "Farmhouse, Cottage",
                    CheckInTime = TimeSpan.FromHours(16),
                    RoomImage = "/Images/rural_farmstay.jpg",
                    CheckOutTime = TimeSpan.FromHours(10),
                    AveragePricePerNight = 150,
                    Rating = 3,
                    Description = "Experience farm life and unwind in the tranquility of the countryside."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 6,
                    Name = "Urban Boutique Hotel",
                    Address = "321 Trendy Street",
                    City = "Hipsterville",
                    PostalCode = "86420",
                    Country = "Trendyland",
                    ContactEmail = "info@urbanboutiquehotel.com",
                    ContactPhone = "+6789012345",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = true,
                    Pool = false,
                    NumberOfRooms = 40,
                    RoomTypes = "Standard, Loft, Penthouse",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/urban_boutique_hotel.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 180,
                    Rating = 4,
                    Description = "Immerse yourself in the vibrant culture of Hipsterville at our trendy boutique hotel."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 7,
                    Name = "Historic Inn",
                    Address = "456 Heritage Lane",
                    City = "Old Town",
                    PostalCode = "97531",
                    Country = "Nostalgia",
                    ContactEmail = "info@historicinn.com",
                    ContactPhone = "+5432198765",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = false,
                    NumberOfRooms = 25,
                    RoomTypes = "Classic Room, Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/historic_inn.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 170,
                    Rating = 3,
                    Description = "Step back in time and stay in a charming historic inn in the heart of Old Town."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 8,
                    Name = "Ski Lodge",
                    Address = "789 Mountain Road",
                    City = "Snowy Peaks",
                    PostalCode = "36984",
                    Country = "Winterland",
                    ContactEmail = "info@skilodge.com",
                    ContactPhone = "+9876543210",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = false,
                    NumberOfRooms = 60,
                    RoomTypes = "Standard, Chalet",
                    CheckInTime = TimeSpan.FromHours(16),
                    RoomImage = "/Images/ski_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 220,
                    Rating = 1,
                    Description = "Hit the slopes and cozy up by the fire at our charming ski lodge."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 9,
                    Name = "Desert Oasis",
                    Address = "321 Sand Dune Drive",
                    City = "Sandy Valley",
                    PostalCode = "75319",
                    Country = "Dunescape",
                    ContactEmail = "info@desertoasis.com",
                    ContactPhone = "+1234567890",
                    Wifi = false,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = true,
                    NumberOfRooms = 30,
                    RoomTypes = "Standard Tent, Deluxe Tent",
                    CheckInTime = TimeSpan.FromHours(14),
                    RoomImage = "/Images/desert_oasis.jpg",
                    CheckOutTime = TimeSpan.FromHours(12),
                    AveragePricePerNight = 160,
                    Rating = 3,
                    Description = "Experience the beauty of the desert and unwind in our luxurious oasis."
                },
                new Hotel.org.Models.Hotels
                {
                    Id = 10,
                    Name = "Lakefront Lodge",
                    Address = "147 Lakeside Avenue",
                    City = "Lakeland",
                    PostalCode = "58204",
                    Country = "Lakelandia",
                    ContactEmail = "info@lakefrontlodge.com",
                    ContactPhone = "+6789012345",
                    Wifi = true,
                    Parking = true,
                    Breakfast = true,
                    Gym = false,
                    Pool = false,
                    NumberOfRooms = 35,
                    RoomTypes = "Standard, Lakeside Suite",
                    CheckInTime = TimeSpan.FromHours(15),
                    RoomImage = "/Images/lakefront_lodge.jpg",
                    CheckOutTime = TimeSpan.FromHours(11),
                    AveragePricePerNight = 190,
                    Rating = 2,
                    Description = "Escape to the serene beauty of the lake and relax at our charming lakefront lodge."
                }
                // Add more hotels as needed
            );
        }
    }
}
